### ISSUE TITLE
Ability for my finely tuned config file

### ISSUE THREAD

**Issue by surminus** [surminus/terragov#14]
We should have a "default", and then be able to overwrite by project name.

For example:

```
default:
  repo_dir: foo
  data_dir: bar
  stackname: blue
  environment: integration

infra-security-groups:
  stackname: govuk
```
